### ISSUE TITLE
Cant generate ttf2towoff error

### ISSUE THREAD

**Issue by Venegrad** [kdydesign/nuxt-fontagon#1]
Invalid member of stdlib 
![image](https://user-images.githubusercontent.com/9676703/97996620-aacf4900-1df0-11eb-9f7d-823d33958b95.png)

**Comment by kdydesign** [comment]
Insufficient information. Could you give me more information?

**Comment by Venegrad** [comment]
im already remove plugin, thats was latest nuxt, and latest npm. windows 10.

**Comment by lna1989** [comment]
@kdydesign  This error is reproduced on Node 14.17.3
![image](https://user-images.githubusercontent.com/49455662/126746028-b2a4d956-1954-4d3c-b332-1225ff069031.png)

**Comment by lna1989** [comment]
@kdydesign  Can we rediscover the task since the problem is relevant? 
Additional information is given above, if you need more information, please tell me how I can help you
