### ISSUE TITLE
Minor: Request to change red logging to another color

### ISSUE THREAD

**Issue by sjstark** [kdydesign/nuxt-fontagon#4]
A very minor request to change the color of the logging of `[BUILD: FONT]` from red to another color (like blue). It's common practice to see red reserved for error logging and another color would help save confusion.

**Comment by kdydesign** [comment]
@sjstark 
Thank you for your request. The requested function will be reflected in the [fontagon ](https://github.com/kdydesign/fontagon) module.

**Comment by kdydesign** [comment]
Upgrade fontagon 1.1.1
